language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: QAt4+m3PpCZf25qnl8qj4S46plGI/qMEOLTTH6fmc2V4Yi7c7ZbW30J7Ruto8j0xnrs8GVPdA8equOWwK73m9HeVwZNR0p91agSKDlQA5plwRjfCbdJpcikJSedewCxhCmh2IdjOvZ4Fc0XPkFLlW4UuZvqXFmZ5QjwFMrluDJbzHvi4uSiuUesppur8FD2WtSAhHaru9SLfXwlkXNblD7/MYS/TwyHtIev8UAjJGMR8IyqihU1dfBhqStrmZlgdG7b23WXdCBWoPRDbXU1bNYnbry2Ck5pXD2Us32D6o4Z0bK0MyKalILZFll5b8ULKYDOWFoBycUTkNx5xl6uDQQBYyQVZvUWD/5zl/EnIwICMEiqMWZcaDgm62tCOOwvI6EkwglBs7/fJuYuwHRLgI4po1qfFe5yUQzwHZimUHh45KngDyEqedtElWcdZucAcYtEF/fGX9rMw1otXRX8dCsjiLTyA2xVKeV/wZDfT8/hioJJ+xKYL6k2N639sMJrvT9G6d1bKWT8U39nBl9OYO9wC9XsomWLYS3ElL6v3XbHSu01bNXaEFxl3OjozIrrqV3okWlZOb2LgQyfr0aaQAIYAW+Rb9AfeVOitiT6FK+lPc0PLMpYZryTnSSwg0BbkXxvFs1p3KtdNbaVkpCsSlDNuAZo5IViNc3K3q1p+oHo=
  app: ml-tk-sellers-cellars
  skip_cleanup: true
  on:
    branch: master
